name: coda_hub
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  youtube_player_flutter: ^8.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  url_launcher: ^6.2.2
  persistent_bottom_nav_bar: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/home.png
    - assets/codahub.png
    - assets/what_to_know.png
    - assets/what_is_prog.png
    - assets/lessons.png
    - assets/vid_lecs.png
    
    - assets/intro.png
    - assets/intro1.png
    - assets/intro2.png
    - assets/intro3.png

    - assets/lesson_list.png
    - assets/video_course.png
    - assets/about_us.png
    - assets/codabot.png
  
    - assets/javascript/javascript.png
    - assets/javascript/gmail.png
    - assets/javascript/slack.png
    - assets/javascript/fb.png
    - assets/javascript/twtr.png
    - assets/javascript/ig.png

    - assets/python/python.png
    - assets/python/ig.png
    - assets/python/dropbox.png
    - assets/python/yt.png
    - assets/python/reddit.png

    - assets/go/go.png
    - assets/go/docker.png
    - assets/go/kubernetes.png
    - assets/go/prometheus.png
    - assets/go/influx_db.png
    - assets/go/terraform.png

    - assets/java/java.png
    - assets/java/android.png
    - assets/java/eclipse.png
    - assets/java/apache.png
    - assets/java/linked_in.png
    - assets/java/minecraft.png

    - assets/kotlin/kotlin.png
    - assets/kotlin/trello.png
    - assets/kotlin/coursera.png
    - assets/kotlin/evernote.png
    - assets/kotlin/square.png
    - assets/kotlin/slack.png 

    - assets/php/php.png
    - assets/php/wordpress.png
    - assets/php/joomla.png
    - assets/php/drupal.png
    - assets/php/magento.png
    - assets/php/phpbb.png

    - assets/c#/c#.png
    - assets/c#/msoffice.png
    - assets/c#/vscode.png
    - assets/c#/unity3d.png
    - assets/c#/azuredevops.png
    - assets/c#/stackoverflow.png

    - assets/swift/swift.png
    - assets/swift/ig.png
    - assets/swift/uber.png
    - assets/swift/linked_in.png
    - assets/swift/waze.png
    - assets/swift/duolingo.png

    - assets/r/r.png
    - assets/r/rstudio.png
    - assets/r/shiny.png
    - assets/r/bioconductor.png
    - assets/r/ggplot2.png
    - assets/r/dplyr.png

    - assets/ruby/ruby.png
    - assets/ruby/ruby_on_rails.png
    - assets/ruby/github.png
    - assets/ruby/shopify.png
    - assets/ruby/airbnb.png
    - assets/ruby/discourse.png

    - assets/c and c++/c and c++.png
    - assets/c and c++/mswindows.png
    - assets/c and c++/adobe.png
    - assets/c and c++/mozilla.png
    - assets/c and c++/mysql.png
    - assets/c and c++/unreal.png

    - assets/matlab/matlab.png
    - assets/matlab/simulink.png
    - assets/matlab/matlab.png
    - assets/matlab/matlab.png
    - assets/matlab/matlab.png
    - assets/matlab/matlab.png

    - assets/typescript/typescript.png
    - assets/typescript/angular.png
    - assets/typescript/msoffice.png
    - assets/typescript/asana.png
    - assets/typescript/slack.png
    - assets/typescript/vscode.png

    - assets/scala/scala.png
    - assets/scala/twtr.png
    - assets/scala/linked_in.png
    - assets/scala/apache.png
    - assets/scala/coursera.png
    - assets/scala/etsy.png

    - assets/sql/sql.png
    - assets/sql/mysqlworkbench.png
    - assets/sql/smms.png
    - assets/sql/oracle.png
    - assets/sql/phpmyadmin.png
    - assets/sql/sqlite.png

    - assets/html/html.png
    - assets/html/gdocs.png
    - assets/html/wordpress.png
    - assets/html/slack.png
    - assets/html/trello.png
    - assets/html/evernote.png

    - assets/css/css.png

    - assets/nosql/nosql.png
    - assets/nosql/couchdb.png
    - assets/nosql/mongodb.png
    - assets/nosql/apache.png
    - assets/nosql/amazon.png
    - assets/nosql/neo4j.png

    - assets/rust/rust.png
    - assets/rust/mozilla.png
    - assets/rust/dropbox.png
    - assets/rust/cloudflare.png
    - assets/rust/redox.png
    - assets/rust/xi.png

    - assets/perl/perl.png
    - assets/perl/cpanel.png
    - assets/perl/perl.png
    - assets/perl/bugzilla.png
    - assets/perl/request_tracker.png
    - assets/perl/movable.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
